In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
# Sentences
sent=['the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developper',
    'understand the meaning of words',
    'you videos are good']

In [2]:
# Define the vocabulary size
voc_size=10000

In [7]:
# One hot representation
one_hot_rep=[one_hot(words,voc_size)for words in sent]

In [8]:
one_hot_rep

[[1166, 5534, 8539, 9647],
 [1166, 5534, 8539, 3927],
 [1166, 6129, 8539, 5605],
 [1877, 7682, 8973, 3974, 5438],
 [1877, 7682, 8973, 3974, 7659],
 [4041, 1166, 5019, 8539, 8893],
 [8714, 4486, 2669, 3974]]

In [13]:
# Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)

In [16]:
embedded_docs

array([[   0,    0,    0,    0, 1166, 5534, 8539, 9647],
       [   0,    0,    0,    0, 1166, 5534, 8539, 3927],
       [   0,    0,    0,    0, 1166, 6129, 8539, 5605],
       [   0,    0,    0, 1877, 7682, 8973, 3974, 5438],
       [   0,    0,    0, 1877, 7682, 8973, 3974, 7659],
       [   0,    0,    0, 4041, 1166, 5019, 8539, 8893],
       [   0,    0,    0,    0, 8714, 4486, 2669, 3974]])

In [17]:
# Feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 136ms/step


array([[[ 0.01683379,  0.04313221, -0.00722742, -0.03867586,
         -0.00367073, -0.03172326,  0.03986007,  0.0489147 ,
         -0.00216191,  0.03647989],
        [ 0.01683379,  0.04313221, -0.00722742, -0.03867586,
         -0.00367073, -0.03172326,  0.03986007,  0.0489147 ,
         -0.00216191,  0.03647989],
        [ 0.01683379,  0.04313221, -0.00722742, -0.03867586,
         -0.00367073, -0.03172326,  0.03986007,  0.0489147 ,
         -0.00216191,  0.03647989],
        [ 0.01683379,  0.04313221, -0.00722742, -0.03867586,
         -0.00367073, -0.03172326,  0.03986007,  0.0489147 ,
         -0.00216191,  0.03647989],
        [ 0.03008181, -0.03316828, -0.00712879,  0.04661567,
          0.01870611, -0.04883964,  0.02188322,  0.01308144,
         -0.0101015 , -0.01913465],
        [ 0.0387259 , -0.00846404,  0.0215295 , -0.01467887,
         -0.02622956, -0.04255241, -0.03422225,  0.01228912,
          0.03784731, -0.03676242],
        [ 0.0253158 ,  0.04295889,  0.01188999, -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 1166, 5534, 8539, 9647])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 45ms/step


array([[ 0.01683379,  0.04313221, -0.00722742, -0.03867586, -0.00367073,
        -0.03172326,  0.03986007,  0.0489147 , -0.00216191,  0.03647989],
       [ 0.01683379,  0.04313221, -0.00722742, -0.03867586, -0.00367073,
        -0.03172326,  0.03986007,  0.0489147 , -0.00216191,  0.03647989],
       [ 0.01683379,  0.04313221, -0.00722742, -0.03867586, -0.00367073,
        -0.03172326,  0.03986007,  0.0489147 , -0.00216191,  0.03647989],
       [ 0.01683379,  0.04313221, -0.00722742, -0.03867586, -0.00367073,
        -0.03172326,  0.03986007,  0.0489147 , -0.00216191,  0.03647989],
       [ 0.03008181, -0.03316828, -0.00712879,  0.04661567,  0.01870611,
        -0.04883964,  0.02188322,  0.01308144, -0.0101015 , -0.01913465],
       [ 0.0387259 , -0.00846404,  0.0215295 , -0.01467887, -0.02622956,
        -0.04255241, -0.03422225,  0.01228912,  0.03784731, -0.03676242],
       [ 0.0253158 ,  0.04295889,  0.01188999, -0.03974878,  0.02926054,
         0.03625187,  0.03494293, -0.01321293

Chaque mot est converti en un vecteur de dimension 10 dans une phrase de longueur 8